// kaelAu.js — built-in clean continuity for the Kael reaction-room AU.
// This seed is intentionally separate from the original Joseph/Anya workspace.

export const KAEL_AU_PROJECT = { id:'kael-au', name:'Power to Strive — Kael AU' };

const sharedKnowledge = 'Timeline: approximately two days before the 57th Expedition. Does NOT know that Annie/Reiner/Bertolt are enemies, Ymir is a Titan, Christa is Historia Reiss, the Reiss family is the true royal family, humanity exists outside the Walls, Marley exists, Levi is an Ackerman, what is in Eren’s basement, or the complete origin of Titans. Future facts become known only after the screen explicitly reveals them.';

export const KAEL_AU_CHARACTERS = [
{name:'Petra Ral',pronouns:'she/her',personality:'Warm, experienced Scout; emotional translator and practical observer. Bridges senior officers and cadets without becoming mere comfort. Notices discipline, formations, teamwork, overwhelmed people, Levi’s intent beneath rude wording, and the human cost of command.',speechStyle:'Calm, respectful, direct, occasionally playful. Simple strong observations rather than speeches.',hardRules:'Experienced and tactically competent. May disagree with Levi. Concern often appears as practical help.',currentKnowledge:sharedKnowledge,relationships:'Professional trust with Levi; mentor/older-sister energy with Eren; respects Erwin while noticing costs; amused/exhausted by Hange; sees Jean’s leadership potential.',chemistry:'With Kael, initially evaluates him through Levi and notices early that Levi is unusually comfortable around him. With Erwin and Levi, reads small changes without forcing them into public confession.',neverDoRules:'Do not make her blindly agree with Levi, exist only to comfort Eren, constantly blush around Levi, be naive about death, or be too fragile for strategy.',active:true},
{name:'Erwin Smith',pronouns:'he/him',personality:'Organizer of meaning. Strategic, political, controlled and precise. Asks why information is shown, who benefits, what can be changed, and what must remain temporarily.',speechStyle:'Calm, formal without being robotic; often asks precise questions rather than announcing feelings. More uncomfortable means more professional.',hardRules:'Levi’s former lover. Their serious relationship ended before the room because command/subordinate pressures became untenable, not betrayal or lack of care. He has no claim over Levi now and must never become a cartoonishly jealous ex.',currentKnowledge:sharedKnowledge+' Knows his own past relationship with Levi. Does not initially know the exact nature of Levi and Kael’s current intimacy.',relationships:'Exceptional trust and old intimacy with Levi; intellectual partnership with Hange; tests Armin’s reasoning; sees Jean’s leadership; trusts Petra’s practical judgment.',chemistry:'With Levi, practiced boundaries overlay deep familiarity; a glance can replace a conversation. With Kael, first assesses identity, access, reliability and motive. Learning Kael has slept with Levi can hurt despite Erwin knowing Levi did nothing wrong; his defense is increased professionalism, including conspicuous “Captain Levi.”',neverDoRules:'Do not make him emotionless, always correct, manipulative for entertainment, openly possessive, or philosophical in every reaction.',active:true},
{name:'Hange Zoë',pronouns:'they/them',personality:'Scientist, commander and veteran; generator of questions, theories and emotional chaos. Energetic without being reduced to Titan-crazy comic relief.',speechStyle:'Fast and excited during discoveries; playful in jokes; sharp when confronting cruelty; unexpectedly gentle when realizing a line was crossed.',hardRules:'Knows Levi and Erwin’s past relationship. May notice Kael/Levi familiarity early but must protect privacy once teasing becomes harmful.',currentKnowledge:sharedKnowledge+' Knows Levi and Erwin used to be together.',relationships:'Hostile-sounding friendship and deep trust with Levi; intellectual partnership with Erwin; Petra regulates their excesses; enjoys Armin’s theories.',chemistry:'Kael’s resistance to Levi-induced fear fascinates Hange. They notice liberties Levi allows Kael and become suspicious before most cadets.',neverDoRules:'Do not make Hange shout constantly, ignore suffering, be casually unethical, perfectly understand every emotion, or joke through every serious beat.',active:true},
{name:'Levi',pronouns:'he/him',personality:'Practical reality check. Blunt, dry, economical, observant and action-oriented. Notices body positioning, hesitation, injuries, lies, threats and plans dependent on luck. Understands care through trust, presence, responsibility and choices more easily than labels.',speechStyle:'Brief, dry, sarcastic; vulgar when irritated. Concern often sounds like an order or criticism. No long emotional monologues.',hardRules:'MALE in this AU. Erwin is his former lover; breakup came from command pressures, not betrayal. Kael is an established informant contact and trusted outsider. Levi and Kael are consenting adults who have slept together more than once, with no exclusivity agreement or established romantic label. Levi and Kael are NOT married. Joseph and Anya do not exist in this continuity.',currentKnowledge:sharedKnowledge+' Knows his full personal history with Erwin and his own history with Kael.',relationships:'Former serious relationship with Erwin; hostile friendship with Hange; professional trust in Petra; harsh mentor to Eren; listens to Armin when logic is sound. Kael is useful, competent, discreet, irritating, reliable and unusually close.',chemistry:'With Erwin, boundaries not amnesia: automatic trust/protection and compressed familiarity remain. With Kael, quiet familiarity, chosen touch, tea, intelligence work and physical intimacy require little performance. Kael knows some habits, old injuries and what Levi’s silences mean. Levi does not see a contradiction between this and his past with Erwin.',neverDoRules:'Never make Levi female in this AU. Do not make him constantly insulting, cruelty-loving, openly gushy, emotionally empty, cleaning-obsessed, ashamed that sex exists, or secretly already desperately in love with Kael unless the story develops it.',active:true},
{name:'Ymir',pronouns:'she/her',personality:'Detector of hypocrisy, false identities, shame and hidden feelings. Sarcastic, provocative, emotionally sharp; understands vulnerable secrets.',speechStyle:'Informal, cutting, short. Gentle with Historia. Uses sarcasm more when personally exposed.',hardRules:'May infer Levi/Kael intimacy early but does not recklessly expose vulnerable secrets.',currentKnowledge:sharedKnowledge,relationships:'Protective and soft with Historia; blunt respect with Levi; challenges Armin’s intellectualizing; insult-rivalry with Jean.',chemistry:'Notices Levi is irritated rather than truly defensive around Kael and sees residual emotional history with Erwin. Enjoys other people’s delayed comprehension.',neverDoRules:'Do not make her cruel to Historia for fun, sarcastic every line, casually reveal her Titan identity, purely selfish, sentimental to everyone, or omniscient.',active:true},
{name:'Historia Reiss / Christa Lenzz',pronouns:'she/her',personality:'At entry still performing Christa: kind, agreeable, useful and self-sacrificing. Historia’s directness and anger should emerge gradually. Notices quiet suffering, unfairness, loneliness, children and belonging.',speechStyle:'Christa is gentle, apologetic and encouraging; emerging Historia is more direct, passionate and willing to disagree.',hardRules:'Her true identity is not known to the room at opening unless the screen later reveals it.',currentKnowledge:sharedKnowledge,relationships:'Ymir is her anchor; warm with Sasha/Connie; Petra feels safe; uneasy around royal politics she does not yet understand.',chemistry:'In the Levi/Erwin/Kael situation, focuses less on “who should be with whom” and more on loneliness, restraint and whether people are being hurt.',neverDoRules:'Do not make her stupidly innocent, endlessly agreeable, constantly crying, instantly accepting royal identity, or suddenly fully assertive.',active:true},
{name:'Sasha Braus',pronouns:'she/her',personality:'Instinctive observer and tension-breaker; funny but alert and competent. Notices food, sounds, hunting, rural environments, hunger, exhaustion and danger to families.',speechStyle:'Polite when nervous, blunt when comfortable, occasionally strange and unexpectedly perceptive.',hardRules:'In danger she becomes focused and competent; grief can show through loss of appetite.',currentKnowledge:sharedKnowledge,relationships:'Natural comedy/support pair with Connie; warm with Historia; respects Petra; Hange can create dangerous comedy.',chemistry:'May understand that Levi and Kael are comfortable together before understanding why, and can accidentally say something painfully perceptive.',neverDoRules:'Do not make her only about food, unable to understand seriousness, cowardly, or joking through every death.',active:true},
{name:'Connie Springer',pronouns:'he/him',personality:'Ordinary-person perspective. Direct, tactless at times, emotionally transparent; notices familiar people, changed behavior, family/home and socially obvious contradictions.',speechStyle:'Casual, quick jokes, asks the question others are too embarrassed to ask.',hardRules:'Not stupid. Can remember explanations and become completely serious around family, home and betrayal.',currentKnowledge:sharedKnowledge,relationships:'Comedy/support with Sasha; banter with Jean/Eren; relies on Armin for complex explanations.',chemistry:'A prime candidate to eventually ask “Wait. How exactly do you two know each other?” only after enough Levi/Kael evidence has accumulated.',neverDoRules:'Do not make him totally stupid, childlike, forget everything, joke through tragedy, or have no opinions.',active:true},
{name:'Jean Kirstein',pronouns:'he/him',personality:'Skeptical realist and moral challenger. Questions reckless plans, unfair sacrifice and heroic rhetoric; practical, defensive and compassionate underneath.',speechStyle:'Sarcastic, embarrassed, practical. Complaints can become leadership when action is required.',hardRules:'Can disagree with Eren without being his enemy. Growing respect should coexist with rivalry.',currentKnowledge:sharedKnowledge,relationships:'Rivalry/respect with Eren; protective of Armin; intimidated by and respectful of Levi; sees consequences others romanticize.',chemistry:'Likely realizes the Levi/Kael implication after Hange/Ymir but before Connie. Initial reaction is embarrassment, not judgment; may defend Levi if others become disrespectful.',neverDoRules:'Do not make him cowardly, Mikasa-obsessed, always opposed to Eren, always morally correct, or insulting without care.',active:true},
{name:'Mikasa Ackerman',pronouns:'she/her',personality:'Attachment-driven protector. Reactions often happen physically before verbally. Controlled, literal, observant of threats, injuries, combat efficiency and protective patterns.',speechStyle:'Brief, controlled and literal; cold when angry, soft with very few people.',hardRules:'Does not know she and Levi are Ackermans in any meaningful shared-clan sense beyond what canon has established at this timeline.',currentKnowledge:sharedKnowledge,relationships:'Eren and Armin are family; conflict/mirroring with Levi; can value Jean; Ymir challenges her attachment.',chemistry:'May recognize Levi’s automatic attention toward Erwin as a protective pattern resembling her own, while noticing his comfort with Kael manifests differently.',neverDoRules:'Do not make her say Eren every line, attack harmless jokes, ignore Armin, lack strategy, become emotionless, or show violent comic jealousy.',active:true},
{name:'Armin Arlert',pronouns:'he/him',personality:'Interpreter and theory-builder. Connects clues and inconsistencies without instantly solving every mystery. Compassionate, tentative when uncertain, increasingly confident with evidence.',speechStyle:'Careful, evidence-based, concise when possible. Under pressure can become frighteningly strategic.',hardRules:'Must not become omniscient. He accumulates evidence and can be wrong.',currentKnowledge:sharedKnowledge,relationships:'Eren/Mikasa are family; intellectual/moral partnership with Jean; sees Erwin as strategic mentor; shares curiosity with Hange; nervous around Levi but heard by him.',chemistry:'Does not instantly conclude Levi and Kael are sleeping together. Accumulates familiarity, knowledge, Hange/Ymir reactions and Erwin’s formality until the obvious conclusion arrives—and he wishes he had analyzed less efficiently.',neverDoRules:'Do not make him omniscient, explain every obvious thing, deliver giant lectures mid-action, helpless always, eternally innocent, or always rescued.',active:true},
{name:'Eren Yeager',pronouns:'he/him',personality:'Emotional engine. Direct, passionate, impatient; notices injustice, captivity, sacrifice for him, threats to Mikasa/Armin, his father and the basement. Where Erwin wants a plan, Eren wants to stop it.',speechStyle:'Direct, passionate, sometimes rude; thoughtful after calming down. Fear often becomes anger; grief can make him quiet.',hardRules:'He is young and intense, not angry in every scene. He can understand strategy after the first emotional impact.',currentKnowledge:sharedKnowledge,relationships:'Mikasa/Armin are family; rivalry/respect with Jean; harsh mentorship under Levi; admires and is uneasy with Erwin’s willingness to sacrifice.',chemistry:'Initially evaluates Kael by one question: does Captain Levi trust him? Often later than others to catch sexual subtext because he is looking for strategic danger.',neverDoRules:'Do not make him angry every scene, morally certain, automatically hate Levi for cruel choices, ignore strategy, instantly understand politics, or blame others more than himself.',active:true},
{name:'Kael',pronouns:'he/him',personality:'Outsider who knows Levi from a different world. Observant, self-contained, intelligent without performing intelligence, dryly funny, emotionally perceptive, difficult to intimidate, comfortable around morally complicated people, capable of necessary violence without swagger, protective without possessiveness.',speechStyle:'Dry, controlled, occasionally provocative, rarely hurried. Respects rank without being impressed. Gives no unnecessary explanations.',hardRules:'One of Levi’s established informant contacts. Works Underground/merchant/smuggler/corrupt-official/information networks the Scouts cannot openly access. He and Levi are consenting adults who have slept together more than once but are not married, exclusive, or an established romantic couple. He does not compete with Erwin or claim Levi.',currentKnowledge:sharedKnowledge+' Knows his own history with Levi and enough to know Erwin mattered to Levi, but not necessarily every detail of their past.',relationships:'Trust with Levi accumulated through reliability; physical intimacy came later. Initially an outsider to the reaction-room cast. Can develop reluctant mutual respect with Erwin.',chemistry:'With Levi, neither requires performance: they can disappear for weeks, share silence, sleep together, then discuss intelligence over tea. Kael knows a less-armored Levi: habits, light sleep, old injuries, dislike of unexpected touch. With Erwin, quickly realizes “Oh. This is inconvenient,” without smugness or territoriality.',neverDoRules:'Do not make him a smug replacement boyfriend, publicly flirt nonstop, humiliate Erwin, know every secret, become jealous whenever Levi protects Erwin, be perfect at everything, dominate the ensemble, explain Levi’s feelings, claim ownership, or inherit Joseph’s old biography.',active:true}
];

export const KAEL_AU_LOCKED_FACTS = [
'KAEL AU HARD CONTINUITY LOCK: Levi is male and uses he/him. Anya does not exist in this continuity. Joseph does not exist in this continuity. Kael is a separate AU character and must never inherit Joseph/Anya family history.',
'Levi and Erwin are former romantic partners. Their relationship was genuine and serious and ended before the reaction room because Commander/subordinate pressures made it untenable—not because of betrayal or lack of care. Boundaries remain; familiarity did not vanish.',
'Kael is one of Levi’s established informant contacts. Levi and Kael are consenting adults who have had a recurring physical/sexual relationship. They are NOT married, not exclusive by established canon, and not an established romantic couple at story opening.',
'Do not reduce Levi, Erwin and Kael to a conventional love triangle. Erwin must not become a territorial jealous ex; Kael must not become a smug replacement boyfriend; Levi must not become nothing but romantic confusion.',
'Reaction-room characters react only from what they currently know, what they personally care about, how they protect themselves emotionally, and their relationship to the person/event onscreen. They are not fans with complete canon knowledge.',
'Story opening timeline is approximately two days before the 57th Expedition. The room does not know the Warrior identities, Ymir’s Titan identity, Christa’s true identity, the Reiss royal truth, outside-Walls humanity, Marley, Levi’s Ackerman nature, Eren’s basement contents, or the complete Titan origin until the screen reveals those facts.',
'Write the reaction fic as professional novel prose, not a transcript. Usually use only 3–4 active voices in a beat; let silence, body language, interruptions and delayed reactions carry meaning. Do not make all characters take turns paraphrasing the screen.',
'Kael’s relationship with Levi must be discovered gradually through behavior and context. Candy must not simply announce that they have slept together. Accumulate familiarity first: first-name use, permitted closeness, private knowledge, tea/habits, Hange/Ymir/Petra noticing, Armin reconstructing, Erwin becoming more formal.',
'Romance must pass through characterization; characterization must never be replaced by romance.'
];

export const KAEL_AU_CANON = [
{visibility:'private',text:'Levi and Erwin used to be lovers. Command pressures, dangerous orders and Erwin’s concern that personal attachment could distort military judgment contributed to their breakup. Levi resented the implication that he could not separate personal loyalty from professional judgment. Neither side was wholly fair or wholly wrong.'},
{visibility:'private',text:'Kael’s work reaches Underground contacts, merchants, smugglers, loose-tongued officials, information sellers and people involved in human trafficking. Levi uses him because his information has repeatedly proven reliable; Kael continues working with Levi partly because Levi does not treat informants as disposable after delivery.'},
{visibility:'private',text:'Levi and Kael’s physical relationship developed after professional trust. There was no confession, exclusivity agreement or promise. Attraction, trust and affection exist; whether it becomes love is deliberately unresolved and must develop through the story.'},
{visibility:'private',text:'When Kael first enters the room, Levi’s first response is threat assessment: why Kael is here, who brought him, what Candy knows, whether networks are compromised, and what the screen may reveal. Only afterward does he confront that Kael knows private things about him.'},
{visibility:'private',text:'Suggested discovery rhythm: Hange becomes suspicious; Ymir reaches the likely implication; Petra understands; Armin confirms the pattern; Jean realizes and regrets realizing; Mikasa understands without caring about scandal; Sasha grasps comfort before terminology; Connie eventually asks the socially disastrous direct question; Eren catches up later. Erwin likely understands earlier than most and says little.'}
];

export const KAEL_AU_AUTHOR_BRAIN = {
  customGuidance:`KAEL AU reaction-room prose rules:
- Write like a novel, never a reaction transcript or screenplay.
- Preserve individual speech rhythms and epistemic limits.
- Usually let only 3–4 voices lead a reaction beat.
- Personal reaction → emotional observer → analysis → strategic consequence → optional tension release is a useful rhythm, not a mandatory template.
- Battle/tactics: Levi, Petra, Jean, Erwin, Mikasa tend to lead.
- Titan mystery: Hange, Armin, Erwin, Ymir, Eren tend to lead.
- Political reveal: Erwin, Armin, Hange, Jean, Historia; Levi focuses on arrests, assassination, extraction and protection; Kael contributes when corruption/Underground/information networks matter.
- Embarrassing beats: Connie, Sasha, Jean, Hange, Ymir; Levi often ends the chaos.
- Death: prioritize those closest to the victim; silence and physical reactions can replace dialogue.
- Do not translate gestures into explanatory themes. Do not summarize what everyone learned at scene ends.
- Kael is an outsider first, not a romance delivery device.
- Levi/Erwin interactions are not automatically longing. Levi/Kael interactions are not automatically sexual.
- Never import Joseph, Anya, female-Levi, marriage, parenthood, or domestic-family history from another AU.
- Narration/pacing target: polished book-like prose, measured scene breathing, interiority, sensory atmosphere, subtext, clean transitions, and precise physical action. Style references may influence narration/pace only; never copy their plot, phrases, relationships or events.`
};

export async function ensureKaelAuWorkspace(db){
  const saved = await db.get('settings','workspaces') || {id:'workspaces',items:[]};
  if(!saved.items.some((p)=>p.id===KAEL_AU_PROJECT.id)){
    saved.items.push({...KAEL_AU_PROJECT});
    await db.put('settings',saved);
  }
  const marker='kael-au-seed:v1';
  if(await db.get('settings',marker)) return false;
  const previous=db.getActiveProjectId();
  db.setActiveProjectId(KAEL_AU_PROJECT.id);
  try{
    for(const character of KAEL_AU_CHARACTERS) await db.put('characters',{...character});
    for(const text of KAEL_AU_LOCKED_FACTS) await db.put('lockedFacts',{text,isCore:true});
    for(const note of KAEL_AU_CANON) await db.put('canonNotes',{...note,createdAt:new Date().toISOString()});
    await db.put('settings',{id:'author-brain:'+KAEL_AU_PROJECT.id,...KAEL_AU_AUTHOR_BRAIN,feedbackCounts:{},editSignals:{approvals:0,substantialEdits:0,totalReduction:0}});
    await db.put('settings',{id:marker,done:true,createdAt:new Date().toISOString()});
  } finally {
    db.setActiveProjectId(previous);
  }
  return true;
}
